{% set name = "pyexodus" %}
{% set version = "0.1.6" %}
{% set sha256 = "c6f1d6a933721d0c5e12b7942588059aabe471e3c70f1f792d865fa708aa22bb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - numpy
    - h5netcdf

test:
  imports:
    - pyexodus
  requires:
    - python {{ python_min }}
    - pytest
    - flake8
  commands:
    - pytest --pyargs pyexodus

about:
  home: https://salvushub.github.io/pyexodus/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Create Exodus files with Python'

  description: |
    Pure Python module for reading and writing Exodus mesh files.
  doc_url: https://salvushub.github.io/pyexodus/
  dev_url: https://github.com/SalvusHub/pyexodus

extra:
  recipe-maintainers:
    - krischer
