{% set name = "pyexodus" %}
{% set version = "0.1.7" %}
{% set sha256 = "37d19b3a22bfd220e90b16ab616f82b3dd9b453714b5c7fd9bcb97316ee5786f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}.*
    - pip
    - setuptools >=61.0
    - setuptools-scm >=8.0
  run:
    - python >={{ python_min }}
    - numpy
    - h5netcdf >=0.5.0
    - h5py

test:
  imports:
    - pyexodus
  requires:
    - python {{ python_min }}.*
    - pytest
  commands:
    - pytest --pyargs pyexodus

about:
  home: https://salvushub.github.io/pyexodus/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Create Exodus files with Python'
  description: |
    Pure Python module for reading and writing Exodus mesh files.
  doc_url: https://salvushub.github.io/pyexodus/
  dev_url: https://github.com/SalvusHub/pyexodus

extra:
  recipe-maintainers:
    - krischer
