{% set name = "pyexodus" %}
{% set version = "0.1.3" %}
{% set sha256 = "62c278ce1cd5c762746461b59b01c2db32fc9e93c02ad53c3c02fcbf202bbd88" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - h5netcdf

test:
  requires:
    - pytest
    - flake8
  imports:
    - pyexodus
  commands:
    - pytest --pyargs pyexodus

about:
  home: https://salvushub.github.io/pyexodus/
  license: MIT
  license_family: MIT
  # Remove with next pyexodus release.
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE.txt
  summary: Create Exodus files with Python

  description: |
    Pure Python module for reading and writing Exodus mesh files.
  doc_url: https://salvushub.github.io/pyexodus/
  dev_url: https://github.com/SalvusHub/pyexodus

extra:
  recipe-maintainers:
    - krischer
