travis:
  secure:
    BINSTAR_TOKEN: l2VuWswBJPbV0iXiyYg6j2ZsJkkSEQdkwdgpy+464+C8PzXCdWUOTMGozQTsr2eYGJIFkBcRDAIAaoRTW7QerOUHkNhFJotxt5GMiXOuVDbFVZ7IPMYRRvQq7Cf6LUwjPDxD9w/cB14Wa1zaI5CNNCtjugtl+Paw+8YQ5zqQKDnn+nQWnbCL660eslt7A31WWmGCEyojGWDKLllcsX+COZSdqD5V0SChYwNQ57W9my/nMU4xnO03t2+7g5/gomvcDt6ikZ7VHaO5ykEMznepMncF1QK7Z3eHNtBDUyuyn2XAsJksHZEDThWQFM7+zMxQE8f3MubGhGoXv8u1FH4mJygFmFaGwR6sbd42r2Vj6C4eCe2mufnuBEPGB/os8wL9cu/FHQNEcEMEwDdsgBlQ5CuU6cTDWn1kGwmrKo0nB5bcSQpjFTT1QN0yt9jHj+hVYBp08OfQE3bDO9Cs4eKkTs5YS6fPD5Lwr/nUzdStVm2bxZswXTZTj2N2i/vre8IGSY8cBUzubxDPdERHsde+uDSlcXw1uBAYTpv7Gri/QwnloLW+LY2OCdxMc5aiFH7XbFZG/r2k22u2xlQojg4cIcLbPvAqsg/yD5nWSl6khtV0CmX+m2D6oR3SO2WmdsfLSPOUm8Vm+Bk0RxrsKLH2g2Ah80TDesZS1yMztaiHjtY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
