travis:
  secure:
    BINSTAR_TOKEN: fh8uRUpRd2UqwiwaIbwDRVHu+A24Aanr39WfamAbvjrQk3G67MAhtPPvc/k9Euz+EIcmyBfGdTyb2Qd7ZCWQZdcyjV9/Lx1T0yHx58y62gPFhQTavMjoSibzpsCaN9OL+wYXWnV6d1fysbyesLGqF4otAIfR2hrfMmyaQt07L4TqGj1bJoCmLPhV3LcMhobnFupxsoiHux7zDyjWXaCrrs6fObQoOJGJ4pU5+eB1pMWVA9W6cdgPwVYbknXJ5W7kzFF9LkuTPZkRIdlseO1Zw/OJLNeMDYBwfIN3dyI38tk/keATNhi00mbGEuHsI8UOaXOjyZ5yJYk7ugKPvpXiT20GG1UdW3bbWiVql0qBZAp2Vgcq839OCeKv7v+JIQwxzMX+v0EGUHBEulTYuIwXnAhpNqtCXIMyDaID2Q8YjajYJ9CUqyZBVZ4tnuDuCZWQroolUUBBH9IVXxGrLbxc2Y6SV/1fiRP2k9VEHGJnjy3oKVBjW5R0dFfXkFmiGlUy6/f8tD8ZyEaVRDQ0ojyR6k8wN3LaZQ7NxmO54z5fizlTsvUddjGBqQCNeGtwspNlSbLjmdAue7fVaoeHrlQb5tRizpfWWv8zU7Cbn2HObpqgpP5U47V2fX09PmQa1bmYFoXgm7HjybTy2n8ksc6CQFfrwZJDjOjLEBRvDJg2KFQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
